version: '3'
services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: apibara
      MONGO_INITDB_ROOT_PASSWORD: apibara
    ports:
      - 27017:27017
    volumes:
      - ./_docker/apibara_mongodb:/data/db

  myapp:
    image: quay.io/apibara/cli:latest
    volumes:
      - ~/apibara-starknet/typescript-test:/data
    command: ["run", "/data/script.ts", "-A", "dna_key"]
    depends_on:
      - mongo
